{% set name = "matplotcheck" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 92c247854b6c48f8e53029ce72efe09565984186076af692b3db4ad9516efdfd

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy >=1.14.0
    - folium
    - geopandas
    - matplotlib-base
    - rasterio
    - scipy

test:
  imports:
    - matplotcheck
    - matplotcheck.cases
    - matplotcheck.folium
    - matplotcheck.notebook
    - matplotcheck.timeseries
    - matplotcheck.raster
    - matplotcheck.vector

about:
  home: http://github.com/earthlab/matplotcheck
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A package for testing different types of matplotlib plots.'

  description: |
    A set of classes and methods to test various aspects of plots. Designed to
    support autograding of plots in the classroom. This package is maintained
    by Earth Lab and was inspired by Jess Hamrick's plotchecker package.
  doc_url: http://matplotcheck.readthedocs.io/
  dev_url: https://github.com/earthlab/matplotcheck

extra:
  recipe-maintainers:
    - lwasser
